const fs = require('fs');
const base = 'C:/Users/Jithendra Krishna/Downloads/klk/kvr-agro-gardens';
let gallery = fs.readFileSync(base + '/src/data/gallery.ts', 'utf8');

const alts = [
  'Beautiful lush garden landscape colorful flower beds stone pathway',
  'Vibrant blooming flowers Kerala garden red hibiscus pink roses',
  'Lush green plant nursery rows healthy plants pots greenhouse',
  'Happy family customers visiting KVR Agro Gardens nursery',
  'Seasonal flower blooms tropical garden morning dew petals',
  'Fruit tree orchard mango guava lemon trees bearing fruits',
  'Professional landscaping decorative stones water feature exotic plants',
  'Beautiful garden decoration colorful planters artistic arrangement',
  'Indoor plant collection modern living room variety houseplants',
  'Vertical garden installation building wall lush living wall',
  'Beautiful terrace garden potted plants outdoor seating city',
  'Organic vegetable garden fresh green vegetables raised beds',
  'Medicinal plant garden Tulsi Aloe Neem Ayurvedic herbs',
  'Creative succulent arrangement decorative containers various colors',
  'Tall palm trees lining garden pathway tropical resort style',
  'Beautiful bonsai tree collection miniature masterpieces ceramic pots',
  'Aromatic herb garden mint basil coriander rosemary thyme',
  'Garden water feature beautiful fountain flowering plants',
  'Scenic garden pathway decorative stepping stones lush greenery',
  'Colorful flower bed arrangement seasonal blooms formal design',
  'Night garden lighting warm fairy lights illuminating garden path',
  'Garden furniture wooden bench table surrounded by plants',
  'Plant sale event KVR Agro Gardens customers browsing nursery',
  'Guided nursery tour visitors learning plant varieties',
  'Rare exotic plants collection unusual foliage patterns colors',
  'Fragrant flower garden jasmine roses lavender aromatic blooms',
  'Shade garden design ferns hostas shade-loving foliage',
  'Drought tolerant garden succulents cacti desert plants rocks',
  'Pet friendly garden design non-toxic plants safe pets',
  'Seasonal garden decoration festive plants ornamental flowers',
  'Garden maintenance service gardener pruning caring plants',
  'New plant arrivals display nursery fresh stock healthy',
  'Customer planting workshop KVR nursery learning pot plants',
  'Garden workshop training session participants learning gardening',
  'Plant potting session nursery staff preparing plants sale',
  'Garden consultation expert horticulturist at nursery',
  'Bulk plant delivery truck loaded healthy plants',
  'Office plant setup service professional installation modern office',
  'Hotel garden design tropical plants resort style landscaping',
  'Resort landscaping poolside gardens tropical foliage',
  'School garden project children learning plant garden',
  'Community garden project families growing vegetables together',
  'Beautiful rooftop garden transformation potted plants seating',
  'Small balcony garden makeover vertical planters hanging pots',
  'Entryway landscaping beautiful potted plants welcoming visitors',
  'Backyard garden transformation lush green makeover',
  'Front garden design colorful flowers ornamental shrubs',
  'Poolside garden tropical plants palm trees resort vibe',
  'Natural pest control organic solutions plant health',
  'Organic composting kitchen waste garden clippings',
  'Seed sowing workshop learning plant seeds trays',
  'Garden harvest day fresh vegetables fruits collected',
  'Plant propagation workshop growing plants cuttings',
  'Garden photography capturing beauty blooming flowers',
  'KVR Agro Gardens team photo staff workers nursery',
  'KVR Agro Gardens nursery entrance plants greenery welcome',
  'Eco-friendly plant packaging safe delivery biodegradable materials',
  'Safe secure plant delivery custom boxes shipping',
  'Customer unboxing plant order excitement happiness',
  'Happy plant parent showing off indoor plant collection',
  'Garden party decoration plants flowers greenery theme',
  'Wedding garden setup floral decorations green backdrop',
  'Festival garden decoration traditional flowers rangoli',
  'Monsoon garden care tips protecting plants rainfall',
  'Summer garden care tips protecting plants heat sun',
  'Winter garden blooms colorful flowers cold season',
  'Spring flower show vibrant colorful blooms display',
  'Autumn garden colors warm tones yellow orange red',
  'Tropical garden design exotic plants palms colorful flowers',
  'Butterfly garden attract butterflies nectar flowers',
  'Bird friendly garden plants attract birds habitat',
  'Pollinator garden bee-friendly flowers biodiversity',
  'Beautiful cactus collection various shapes sizes flowering',
  'Fern garden different fern varieties lush green',
  'Bamboo grove tall green bamboo stems peaceful',
  'Orchid house many blooming orchids different colors',
  'Hydroponic setup soilless gardening modern growing system',
  'Greenhouse interior rows healthy plants automatic irrigation',
  'Shade net nursery protecting young plants sunlight',
  'Garden tools equipment display watering cans shears',
  'Beautiful pottery collection decorative planters various colors',
  'Decorative planters pots display artistic containers indoor',
  'Garden art sculpture decoration artistic elements garden',
  'Garden water fountain centerpiece flowering plants',
  'Koi pond colorful fish aquatic plants serene garden',
  'Rock garden decorative stones succulents alpine plants',
  'Japanese garden zen elements bamboo water feature moss',
  'Cottage garden romantic flowers rustic elements',
  'Modern garden clean lines minimalist planting contemporary',
  'Minimalist garden simple elegant planting geometric design',
  'Tropical paradise exotic palms vibrant flowers lush foliage',
  'Desert landscape cacti succulents drought tolerant plants',
  'Moss garden soft green moss rocks ground zen',
  'Green living fern wall lush ferns natural texture',
  'Living wall automated irrigation vertical garden technology',
  'Green building facade climbing plants exterior wall',
  'Garden bench seating area surrounded flowering plants',
  'Reading nook garden comfortable seating shaded trees plants',
  'Meditation garden peaceful design calming plants quiet seating',
  'Yoga garden space wooden deck surrounded plants flowers',
  'Children play garden safe plants natural playground',
  'Edible garden vegetables fruits herbs growing beautifully',
  'Kitchen garden harvest basket fresh vegetables fruits herbs',
  'Farm to table concept fresh garden produce healthy',
  'Fresh garden produce display organically grown vegetables',
];

for (let i = 0; i < alts.length; i++) {
  const seed = 501 + i;
  const prompt = encodeURIComponent(alts[i] + ' photorealistic');
  const newUrl = 'https://image.pollinations.ai/prompt/' + prompt + '?width=800&height=600&nologo=true&seed=' + seed;
  const regex = new RegExp('src: "https://image\\.pollinations\\.ai/prompt/[^"]*seed=' + seed + '"');
  gallery = gallery.replace(regex, 'src: "' + newUrl + '"');
}

fs.writeFileSync(base + '/src/data/gallery.ts', gallery);
console.log('Gallery fixed. Broken remaining: ' + (gallery.match(/%22%2C%20alt/g) || []).length);
